const permissionData = {
    "dashboard": 1,
    "analytics": 0,
    "mapAnalytics": 0,
    "advanceAnalytics": 0,
    "buildOwnReport": 0,
    "report ": 0,
    "registrationReport": 0,
    "odometerReport": 0,
    "stockReport": 0,
    "surveyReport": 0,
    "csrReport": 0,
    "mapping": 0,
    "calender": 0,
    "activity": 0,
    "enquiries": 0,
    "visits": 0,
    "createPjp": 0,
    "pjpSchedule": 0,
    "visitReport": 0,
    "enquiryReport": 0,
    "branding": 0,
    "expenses": 0,
    "scheme": 0,
    "selfService":0,
    "attendenceReport": 0,
    "leaveReport": 0,
    "raiseRequest": 0,
    "masterList": 0,
    "employee": 0,
    "dealer": 0,
    "subDealer": 0,
    "distributor": 0,
    "influencer": 0,
    "product": 0,
    "userSettings": 0,
    "remarks": 0,
    "email": 0,
    "contactSync": 0,
    "mailSignature": 0,
    "notification": 0,
    "followUp": 0,
    "tour": 0,
    "feedback": 0
};

export { permissionData }